/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jhello_Hello */

#ifndef _Included_jhello_Hello
#define _Included_jhello_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jhello_Hello
 * Method:    plus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jhello_Hello_plus
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jhello_Hello
 * Method:    plusone
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jhello_Hello_plusone
  (JNIEnv *, jclass, jint);

/*
 * Class:     jhello_Hello
 * Method:    current_timestamp
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jhello_Hello_current_1timestamp
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
